import "./App.css";
import { useState } from "react";
import { Heading, Card, CardBody, Flex, Container } from "@chakra-ui/react";
import Selector from "./Selector";
import CalendarioTable from "./CalendarioTable";

function App() {
  const [department, setDepartment] = useState("Todos");
  const [month, setMonth] = useState("Todos");
  const [year, setYear] = useState("2024");
  const [order, setOrder] = useState("");

  const departamentos = [
    { id: 1, nome: "Recursos Humanos", idAlternativo: "rh" },
    { id: 2, nome: "Marketing", idAlternativo: "marketing" },
    { id: 3, nome: "Tecnologia", idAlternativo: "tecnologia" },
    { id: 4, nome: "Financeiro", idAlternativo: "financeiro" },
  ];
  const months = ["Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"];
  const years = ["2021", "2022", "2023", "2024", "2025"];

  const funcionarios = [
    { id: "002", nomeAbreviado: "João José" },
    { id: "003", nomeAbreviado: "Maria Dinis" },
    { id: "004", nomeAbreviado: "José Martins" },
    { id: "005", nomeAbreviado: "Ana Ceuta" },
    { id: "006", nomeAbreviado: "Pedro Matoso" },
    { id: "007", nomeAbreviado: "Marta Brasão" },
    { id: "008", nomeAbreviado: "Carlos Fim" },
    { id: "009", nomeAbreviado: "Sofia Fininha" },
    { id: "010", nomeAbreviado: "Rui Mercedes" },
    { id: "011", nomeAbreviado: "Teresa Bragança" },
    { id: "012", nomeAbreviado: "Miguel Macedo" },
    { id: "013", nomeAbreviado: "Diana Pereira" },
    { id: "014", nomeAbreviado: "Ricardo Mendes" },
    { id: "015", nomeAbreviado: "Inês Pimenta" },
    { id: "016", nomeAbreviado: "Hugo Cardoso" },
    { id: "017", nomeAbreviado: "Catarina Gouveia" },
  ];

  const feriasFaltas = [
    {
      id: 0,
      funcionarioId: "002",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-01-02T00:00:00",
      dataFim: "2024-01-02T00:00:00",
      sequencia: 7032,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "002",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-01-24T00:00:00",
      dataFim: "2024-01-23T12:00:00",
      sequencia: 7032,
      diaParcial: true,
      periodo: "",
      tipoFalta: "Falta",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "002",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-02-06T00:00:00",
      dataFim: "2024-02-05T12:00:00",
      sequencia: 7075,
      diaParcial: true,
      periodo: "",
      tipoFalta: "Falta",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "002",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-03-06T00:00:00",
      dataFim: "2024-03-05T12:00:00",
      sequencia: 7116,
      diaParcial: true,
      periodo: "",
      tipoFalta: "Falta",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "002",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-23T00:00:00",
      dataFim: "2024-04-22T12:00:00",
      sequencia: 7206,
      diaParcial: true,
      periodo: "",
      tipoFalta: "Falta",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "002",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-05-21T00:00:00",
      dataFim: "2024-05-20T12:00:00",
      sequencia: 7208,
      diaParcial: true,
      periodo: "",
      tipoFalta: "Falta",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "002",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-05-22T00:00:00",
      dataFim: "2024-05-21T12:00:00",
      sequencia: 7208,
      diaParcial: true,
      periodo: "",
      tipoFalta: "Falta",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "002",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-11T00:00:00",
      dataFim: "2024-06-10T12:00:00",
      sequencia: 7252,
      diaParcial: true,
      periodo: "",
      tipoFalta: "Falta",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "002",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-19T00:00:00",
      dataFim: "2024-06-18T12:00:00",
      sequencia: 7252,
      diaParcial: true,
      periodo: "",
      tipoFalta: "Falta",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "003",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-01-10T00:00:00",
      dataFim: "2024-07-08T12:00:00",
      sequencia: 7296,
      diaParcial: true,
      periodo: "",
      tipoFalta: "Falta",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "004",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-01-16T00:00:00",
      dataFim: "2024-07-08T12:00:00",
      sequencia: 7296,
      diaParcial: true,
      periodo: "",
      tipoFalta: "Falta",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "004",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-01-12T00:00:00",
      dataFim: "2024-07-08T12:00:00",
      sequencia: 7296,
      diaParcial: true,
      periodo: "",
      tipoFalta: "Falta",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "005",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-01-04T00:00:00",
      dataFim: "2024-07-08T12:00:00",
      sequencia: 7296,
      diaParcial: true,
      periodo: "",
      tipoFalta: "Falta",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "005",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-01-07T00:00:00",
      dataFim: "2024-07-08T12:00:00",
      sequencia: 7296,
      diaParcial: true,
      periodo: "",
      tipoFalta: "Falta",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "006",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-01-18T00:00:00",
      dataFim: "2024-07-08T12:00:00",
      sequencia: 7296,
      diaParcial: true,
      periodo: "",
      tipoFalta: "Falta",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "006",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-01-14T00:00:00",
      dataFim: "2024-07-08T12:00:00",
      sequencia: 7296,
      diaParcial: true,
      periodo: "",
      tipoFalta: "Falta",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
  ];

  const feriasPorAprovar = [
    {
      id: 9,
      funcionarioId: "002",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-01-07T00:00:00",
      dataFim: "2025-01-28T00:00:00",
      sequencia: null,
      diaParcial: null,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Solicitação para dia 28 de janeiro",
      comprovativo: null,
      aprovacoes: {
        aprovadorFuncionarioId: 62,
        aprovadoFuncionario: true,
        dataAprovacaoFuncionario: null,
        aprovadorGestorId: null,
        aprovadoGestor: null,
        dataAprovacaoGestor: null,
        aprovadorRHId: null,
        aprovadoRH: null,
        dataAprovacaoRH: null,
        dataPedidoAprovacao: "2025-01-22T09:23:01.40268",
        objetoId: 0,
        tipoEntidadeAprocacao: null,
        justificacaoFuncionario: null,
        justificacaoGestor: null,
        justificacaoRH: null,
      },
    },
    {
      id: 10,
      funcionarioId: "002",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-01-09T00:00:00",
      dataFim: "2025-01-29T00:00:00",
      sequencia: null,
      diaParcial: null,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Solicitação para dia 28 de janeiro",
      comprovativo: null,
      aprovacoes: {
        aprovadorFuncionarioId: 62,
        aprovadoFuncionario: true,
        dataAprovacaoFuncionario: null,
        aprovadorGestorId: null,
        aprovadoGestor: null,
        dataAprovacaoGestor: null,
        aprovadorRHId: null,
        aprovadoRH: null,
        dataAprovacaoRH: null,
        dataPedidoAprovacao: "2025-01-22T09:23:01.40268",
        objetoId: 0,
        tipoEntidadeAprocacao: null,
        justificacaoFuncionario: null,
        justificacaoGestor: null,
        justificacaoRH: null,
      },
    },
    {
      id: 11,
      funcionarioId: "003",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-01-15T00:00:00",
      dataFim: "2025-01-15T00:00:00",
      sequencia: null,
      diaParcial: null,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Solicitação para dia 28 de janeiro",
      comprovativo: null,
      aprovacoes: {
        aprovadorFuncionarioId: 62,
        aprovadoFuncionario: true,
        dataAprovacaoFuncionario: null,
        aprovadorGestorId: null,
        aprovadoGestor: null,
        dataAprovacaoGestor: null,
        aprovadorRHId: null,
        aprovadoRH: null,
        dataAprovacaoRH: null,
        dataPedidoAprovacao: "2025-01-22T09:23:01.40268",
        objetoId: 0,
        tipoEntidadeAprocacao: null,
        justificacaoFuncionario: null,
        justificacaoGestor: null,
        justificacaoRH: null,
      },
    },
    {
      id: 12,
      funcionarioId: "003",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-01-02T00:00:00",
      dataFim: "2025-01-02T00:00:00",
      sequencia: null,
      diaParcial: null,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Solicitação para dia 28 de janeiro",
      comprovativo: null,
      aprovacoes: {
        aprovadorFuncionarioId: 62,
        aprovadoFuncionario: true,
        dataAprovacaoFuncionario: null,
        aprovadorGestorId: null,
        aprovadoGestor: null,
        dataAprovacaoGestor: null,
        aprovadorRHId: null,
        aprovadoRH: null,
        dataAprovacaoRH: null,
        dataPedidoAprovacao: "2025-01-22T09:23:01.40268",
        objetoId: 0,
        tipoEntidadeAprocacao: null,
        justificacaoFuncionario: null,
        justificacaoGestor: null,
        justificacaoRH: null,
      },
    },
    {
      id: 12,
      funcionarioId: "004",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-01-10T00:00:00",
      dataFim: "2025-01-02T00:00:00",
      sequencia: null,
      diaParcial: null,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Solicitação para dia 28 de janeiro",
      comprovativo: null,
      aprovacoes: {
        aprovadorFuncionarioId: 62,
        aprovadoFuncionario: true,
        dataAprovacaoFuncionario: null,
        aprovadorGestorId: null,
        aprovadoGestor: null,
        dataAprovacaoGestor: null,
        aprovadorRHId: null,
        aprovadoRH: null,
        dataAprovacaoRH: null,
        dataPedidoAprovacao: "2025-01-22T09:23:01.40268",
        objetoId: 0,
        tipoEntidadeAprocacao: null,
        justificacaoFuncionario: null,
        justificacaoGestor: null,
        justificacaoRH: null,
      },
    },
  ];

  return (
    <>
      <Heading as="h2" size="md">
        Aprovações de Férias
      </Heading>
      <Card mt="5" p="2">
        <CardBody display="flex" flexDirection="column">
          <Selector
            department={department}
            setDepartment={setDepartment}
            month={month}
            setMonth={setMonth}
            year={year}
            setYear={setYear}
            order={order}
            setOrder={setOrder}
            departamentos={departamentos}
            months={months}
            years={years}
          />
          <Flex>
            <CalendarioTable
              funcionarios={funcionarios}
              selectedMonth={month}
              selectedYear={year}
              feriasFaltas={feriasFaltas}
              feriasPorAprovar={feriasPorAprovar}
            />
          </Flex>
        </CardBody>
      </Card>
    </>
  );
}

export default App;
