import "./App.css";
import { useState } from "react";
import { Heading, Card, CardBody, Flex } from "@chakra-ui/react";
import Selector from "./Selector";
import CalendarioTable from "./CalendarioTable";

function App() {
  const [department, setDepartment] = useState("Todos");
  const [month, setMonth] = useState("Todos");
  const [year, setYear] = useState("2024");
  const [order, setOrder] = useState("");

  const departamentos = [
    { id: 1, nome: "Recursos Humanos", idAlternativo: "rh" },
    { id: 2, nome: "Marketing", idAlternativo: "marketing" },
    { id: 3, nome: "Tecnologia", idAlternativo: "tecnologia" },
    { id: 4, nome: "Financeiro", idAlternativo: "financeiro" },
  ];
  const months = ["Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"];
  const years = ["2021", "2022", "2023", "2024", "2025"];

  const funcionarios = [
    { id: 1, nomeAbreviado: "João José" },
    { id: 2, nomeAbreviado: "Maria Dinis" },
    { id: 3, nomeAbreviado: "José Martins" },
    { id: 4, nomeAbreviado: "Ana Ceuta" },
    { id: 5, nomeAbreviado: "Pedro Matoso" },
    { id: 6, nomeAbreviado: "Marta Brasão" },
    { id: 7, nomeAbreviado: "Carlos Fim" },
    { id: 8, nomeAbreviado: "Sofia Fininha" },
    { id: 9, nomeAbreviado: "Rui Mercedes" },
    { id: 10, nomeAbreviado: "Teresa Bragança" },
    { id: 11, nomeAbreviado: "Miguel Macedo" },
    { id: 12, nomeAbreviado: "Diana Pereira" },
    { id: 13, nomeAbreviado: "Ricardo Mendes" },
    { id: 14, nomeAbreviado: "Inês Pimenta" },
    { id: 15, nomeAbreviado: "Hugo Cardoso" },
    { id: 16, nomeAbreviado: "Catarina Gouveia" },
  ];

  const feriasFaltas = [
    {
      id: 0,
      funcionarioId: "002",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-01-02T00:00:00",
      dataFim: "2024-01-02T00:00:00",
      sequencia: 7032,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "002",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-01-24T00:00:00",
      dataFim: "2024-01-23T12:00:00",
      sequencia: 7032,
      diaParcial: true,
      periodo: "",
      tipoFalta: "Falta",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "002",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-02-06T00:00:00",
      dataFim: "2024-02-05T12:00:00",
      sequencia: 7075,
      diaParcial: true,
      periodo: "",
      tipoFalta: "Falta",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "002",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-03-06T00:00:00",
      dataFim: "2024-03-05T12:00:00",
      sequencia: 7116,
      diaParcial: true,
      periodo: "",
      tipoFalta: "Falta",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "002",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-23T00:00:00",
      dataFim: "2024-04-22T12:00:00",
      sequencia: 7206,
      diaParcial: true,
      periodo: "",
      tipoFalta: "Falta",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "002",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-05-21T00:00:00",
      dataFim: "2024-05-20T12:00:00",
      sequencia: 7208,
      diaParcial: true,
      periodo: "",
      tipoFalta: "Falta",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "002",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-05-22T00:00:00",
      dataFim: "2024-05-21T12:00:00",
      sequencia: 7208,
      diaParcial: true,
      periodo: "",
      tipoFalta: "Falta",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "002",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-11T00:00:00",
      dataFim: "2024-06-10T12:00:00",
      sequencia: 7252,
      diaParcial: true,
      periodo: "",
      tipoFalta: "Falta",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "002",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-19T00:00:00",
      dataFim: "2024-06-18T12:00:00",
      sequencia: 7252,
      diaParcial: true,
      periodo: "",
      tipoFalta: "Falta",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "004",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-29T00:00:00",
      dataFim: "2024-04-29T00:00:00",
      sequencia: 7163,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "004",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-30T00:00:00",
      dataFim: "2024-04-30T00:00:00",
      sequencia: 7163,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "004",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-05-31T00:00:00",
      dataFim: "2024-05-31T00:00:00",
      sequencia: 7209,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "004",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-28T00:00:00",
      dataFim: "2024-06-28T00:00:00",
      sequencia: 7254,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "009",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-03-25T00:00:00",
      dataFim: "2024-03-25T00:00:00",
      sequencia: 7118,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "009",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-03-26T00:00:00",
      dataFim: "2024-03-26T00:00:00",
      sequencia: 7118,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "009",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-03-27T00:00:00",
      dataFim: "2024-03-27T00:00:00",
      sequencia: 7118,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "009",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-03-28T00:00:00",
      dataFim: "2024-03-28T00:00:00",
      sequencia: 7118,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "009",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-01T00:00:00",
      dataFim: "2024-04-01T00:00:00",
      sequencia: 7205,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "029",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-02-19T00:00:00",
      dataFim: "2024-02-19T00:00:00",
      sequencia: 7079,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "029",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-02-20T00:00:00",
      dataFim: "2024-02-20T00:00:00",
      sequencia: 7079,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "043",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-01-04T00:00:00",
      dataFim: "2024-01-04T00:00:00",
      sequencia: 7037,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "043",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-01-05T00:00:00",
      dataFim: "2024-01-05T00:00:00",
      sequencia: 7037,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "043",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-02-12T00:00:00",
      dataFim: "2024-02-12T00:00:00",
      sequencia: 7080,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "043",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-02-14T00:00:00",
      dataFim: "2024-02-14T00:00:00",
      sequencia: 7080,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "043",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-02-23T00:00:00",
      dataFim: "2024-02-23T00:00:00",
      sequencia: 7080,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "043",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-01T00:00:00",
      dataFim: "2024-04-01T00:00:00",
      sequencia: 7167,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "043",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-05-31T00:00:00",
      dataFim: "2024-05-31T00:00:00",
      sequencia: 7213,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "043",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-03T00:00:00",
      dataFim: "2024-06-03T00:00:00",
      sequencia: 7261,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "043",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-04T00:00:00",
      dataFim: "2024-06-04T00:00:00",
      sequencia: 7261,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "043",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-05T00:00:00",
      dataFim: "2024-06-05T00:00:00",
      sequencia: 7261,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "043",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-06T00:00:00",
      dataFim: "2024-06-06T00:00:00",
      sequencia: 7261,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "043",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-07T00:00:00",
      dataFim: "2024-06-07T00:00:00",
      sequencia: 7261,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "044",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-03-28T00:00:00",
      dataFim: "2024-03-28T00:00:00",
      sequencia: 7124,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "044",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-01T00:00:00",
      dataFim: "2024-04-01T00:00:00",
      sequencia: 7170,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "044",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-03-22T00:00:00",
      dataFim: "2024-03-21T12:00:00",
      sequencia: 7124,
      diaParcial: true,
      periodo: "",
      tipoFalta: "Falta",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "044",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-10T00:00:00",
      dataFim: "2024-04-09T12:00:00",
      sequencia: 7170,
      diaParcial: true,
      periodo: "",
      tipoFalta: "Falta",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "050",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-01T00:00:00",
      dataFim: "2024-04-01T00:00:00",
      sequencia: 7171,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "050",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-02T00:00:00",
      dataFim: "2024-04-02T00:00:00",
      sequencia: 7171,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "050",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-03T00:00:00",
      dataFim: "2024-04-03T00:00:00",
      sequencia: 7171,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "050",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-04T00:00:00",
      dataFim: "2024-04-04T00:00:00",
      sequencia: 7171,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "052",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-01T00:00:00",
      dataFim: "2024-04-01T00:00:00",
      sequencia: 7172,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "052",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-02T00:00:00",
      dataFim: "2024-04-02T00:00:00",
      sequencia: 7172,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "052",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-03T00:00:00",
      dataFim: "2024-04-03T00:00:00",
      sequencia: 7172,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "052",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-04T00:00:00",
      dataFim: "2024-04-04T00:00:00",
      sequencia: 7172,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "052",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-05T00:00:00",
      dataFim: "2024-04-05T00:00:00",
      sequencia: 7172,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "053",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-01-02T00:00:00",
      dataFim: "2024-01-02T00:00:00",
      sequencia: 7041,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "053",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-02-15T00:00:00",
      dataFim: "2024-02-15T00:00:00",
      sequencia: 7086,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "053",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-02-16T00:00:00",
      dataFim: "2024-02-16T00:00:00",
      sequencia: 7086,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "053",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-01T00:00:00",
      dataFim: "2024-04-01T00:00:00",
      sequencia: 7173,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "053",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-02T00:00:00",
      dataFim: "2024-04-02T00:00:00",
      sequencia: 7173,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "053",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-03T00:00:00",
      dataFim: "2024-04-03T00:00:00",
      sequencia: 7173,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "053",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-04T00:00:00",
      dataFim: "2024-04-04T00:00:00",
      sequencia: 7173,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "053",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-05T00:00:00",
      dataFim: "2024-04-05T00:00:00",
      sequencia: 7173,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "053",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-05-27T00:00:00",
      dataFim: "2024-05-27T00:00:00",
      sequencia: 7219,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "053",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-05-28T00:00:00",
      dataFim: "2024-05-28T00:00:00",
      sequencia: 7219,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "053",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-05-29T00:00:00",
      dataFim: "2024-05-29T00:00:00",
      sequencia: 7219,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "053",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-05-31T00:00:00",
      dataFim: "2024-05-31T00:00:00",
      sequencia: 7219,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "056",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-01-02T00:00:00",
      dataFim: "2024-01-02T00:00:00",
      sequencia: 7042,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "056",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-02-12T00:00:00",
      dataFim: "2024-02-12T00:00:00",
      sequencia: 7087,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "056",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-02-14T00:00:00",
      dataFim: "2024-02-14T00:00:00",
      sequencia: 7087,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "056",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-03T00:00:00",
      dataFim: "2024-04-03T00:00:00",
      sequencia: 7174,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "056",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-04T00:00:00",
      dataFim: "2024-04-04T00:00:00",
      sequencia: 7174,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "056",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-05T00:00:00",
      dataFim: "2024-04-05T00:00:00",
      sequencia: 7174,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "059",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-01T00:00:00",
      dataFim: "2024-04-01T00:00:00",
      sequencia: 7175,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "059",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-02T00:00:00",
      dataFim: "2024-04-02T00:00:00",
      sequencia: 7175,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "059",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-03T00:00:00",
      dataFim: "2024-04-03T00:00:00",
      sequencia: 7175,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "059",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-04T00:00:00",
      dataFim: "2024-04-04T00:00:00",
      sequencia: 7175,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "059",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-05T00:00:00",
      dataFim: "2024-04-05T00:00:00",
      sequencia: 7175,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "059",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-08T00:00:00",
      dataFim: "2024-04-08T00:00:00",
      sequencia: 7175,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "061",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-08T00:00:00",
      dataFim: "2024-04-08T00:00:00",
      sequencia: 7176,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "061",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-09T00:00:00",
      dataFim: "2024-04-09T00:00:00",
      sequencia: 7176,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "061",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-10T00:00:00",
      dataFim: "2024-04-10T00:00:00",
      sequencia: 7176,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "061",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-11T00:00:00",
      dataFim: "2024-04-11T00:00:00",
      sequencia: 7176,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "061",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-12T00:00:00",
      dataFim: "2024-04-12T00:00:00",
      sequencia: 7176,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "061",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-18T00:00:00",
      dataFim: "2024-06-18T00:00:00",
      sequencia: 7276,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "061",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-19T00:00:00",
      dataFim: "2024-06-19T00:00:00",
      sequencia: 7276,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "061",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-20T00:00:00",
      dataFim: "2024-06-20T00:00:00",
      sequencia: 7276,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "061",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-21T00:00:00",
      dataFim: "2024-06-21T00:00:00",
      sequencia: 7276,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "061",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-07-12T00:00:00",
      dataFim: "2024-07-12T00:00:00",
      sequencia: 0,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "061",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-01-08T00:00:00",
      dataFim: "2024-01-07T12:00:00",
      sequencia: 7044,
      diaParcial: true,
      periodo: "",
      tipoFalta: "Falta",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "067",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-01-02T00:00:00",
      dataFim: "2024-01-02T00:00:00",
      sequencia: 7045,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "067",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-01-03T00:00:00",
      dataFim: "2024-01-03T00:00:00",
      sequencia: 7045,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "067",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-01-04T00:00:00",
      dataFim: "2024-01-04T00:00:00",
      sequencia: 7045,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "067",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-01-05T00:00:00",
      dataFim: "2024-01-05T00:00:00",
      sequencia: 7045,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "067",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-01-08T00:00:00",
      dataFim: "2024-01-08T00:00:00",
      sequencia: 7045,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "067",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-01-09T00:00:00",
      dataFim: "2024-01-09T00:00:00",
      sequencia: 7045,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "067",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-01-10T00:00:00",
      dataFim: "2024-01-10T00:00:00",
      sequencia: 7045,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "067",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-01-11T00:00:00",
      dataFim: "2024-01-11T00:00:00",
      sequencia: 7045,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "067",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-01-12T00:00:00",
      dataFim: "2024-01-12T00:00:00",
      sequencia: 7045,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "067",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-05T00:00:00",
      dataFim: "2024-06-05T00:00:00",
      sequencia: 7278,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "067",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-06T00:00:00",
      dataFim: "2024-06-06T00:00:00",
      sequencia: 7278,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "067",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-07T00:00:00",
      dataFim: "2024-06-07T00:00:00",
      sequencia: 7278,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "077",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-25T00:00:00",
      dataFim: "2024-06-25T00:00:00",
      sequencia: 7280,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "077",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-26T00:00:00",
      dataFim: "2024-06-26T00:00:00",
      sequencia: 7280,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "077",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-27T00:00:00",
      dataFim: "2024-06-27T00:00:00",
      sequencia: 7280,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "077",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-28T00:00:00",
      dataFim: "2024-06-28T00:00:00",
      sequencia: 7280,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "090",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-26T00:00:00",
      dataFim: "2024-04-26T00:00:00",
      sequencia: 7181,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "090",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-07T00:00:00",
      dataFim: "2024-06-07T00:00:00",
      sequencia: 7286,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "094",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-26T00:00:00",
      dataFim: "2024-04-26T00:00:00",
      sequencia: 7182,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "094",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-29T00:00:00",
      dataFim: "2024-04-29T00:00:00",
      sequencia: 7182,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "094",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-30T00:00:00",
      dataFim: "2024-04-30T00:00:00",
      sequencia: 7182,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "097",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-18T00:00:00",
      dataFim: "2024-04-18T00:00:00",
      sequencia: 7183,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "097",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-19T00:00:00",
      dataFim: "2024-04-19T00:00:00",
      sequencia: 7183,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "097",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-22T00:00:00",
      dataFim: "2024-04-22T00:00:00",
      sequencia: 7183,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "097",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-23T00:00:00",
      dataFim: "2024-04-23T00:00:00",
      sequencia: 7183,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "097",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-24T00:00:00",
      dataFim: "2024-04-24T00:00:00",
      sequencia: 7183,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "097",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-26T00:00:00",
      dataFim: "2024-04-26T00:00:00",
      sequencia: 7183,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "097",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-17T00:00:00",
      dataFim: "2024-06-17T00:00:00",
      sequencia: 7290,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "097",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-18T00:00:00",
      dataFim: "2024-06-18T00:00:00",
      sequencia: 7290,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "097",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-19T00:00:00",
      dataFim: "2024-06-19T00:00:00",
      sequencia: 7290,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "097",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-20T00:00:00",
      dataFim: "2024-06-20T00:00:00",
      sequencia: 7290,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "097",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-21T00:00:00",
      dataFim: "2024-06-21T00:00:00",
      sequencia: 7290,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "097",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-25T00:00:00",
      dataFim: "2024-06-25T00:00:00",
      sequencia: 7290,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "097",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-26T00:00:00",
      dataFim: "2024-06-26T00:00:00",
      sequencia: 7290,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "097",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-27T00:00:00",
      dataFim: "2024-06-27T00:00:00",
      sequencia: 7290,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "097",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-28T00:00:00",
      dataFim: "2024-06-28T00:00:00",
      sequencia: 7290,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "099",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-01-08T00:00:00",
      dataFim: "2024-01-08T00:00:00",
      sequencia: 7054,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "099",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-02-12T00:00:00",
      dataFim: "2024-02-12T00:00:00",
      sequencia: 7098,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "099",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-03-27T00:00:00",
      dataFim: "2024-03-27T00:00:00",
      sequencia: 7139,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "099",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-25T00:00:00",
      dataFim: "2024-06-25T00:00:00",
      sequencia: 7294,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "099",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-26T00:00:00",
      dataFim: "2024-06-26T00:00:00",
      sequencia: 7294,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "099",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-27T00:00:00",
      dataFim: "2024-06-27T00:00:00",
      sequencia: 7294,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "099",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-28T00:00:00",
      dataFim: "2024-06-28T00:00:00",
      sequencia: 7294,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "105",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-02-02T00:00:00",
      dataFim: "2024-02-02T00:00:00",
      sequencia: 7099,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "105",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-02-12T00:00:00",
      dataFim: "2024-02-12T00:00:00",
      sequencia: 7099,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "105",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-02-23T00:00:00",
      dataFim: "2024-02-23T00:00:00",
      sequencia: 7099,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "105",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-05T00:00:00",
      dataFim: "2024-06-05T00:00:00",
      sequencia: 7296,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "105",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-13T00:00:00",
      dataFim: "2024-06-13T00:00:00",
      sequencia: 7296,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "105",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-14T00:00:00",
      dataFim: "2024-06-14T00:00:00",
      sequencia: 7296,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "105",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-17T00:00:00",
      dataFim: "2024-06-17T00:00:00",
      sequencia: 7296,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "105",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-18T00:00:00",
      dataFim: "2024-06-18T00:00:00",
      sequencia: 7296,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "105",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-19T00:00:00",
      dataFim: "2024-06-19T00:00:00",
      sequencia: 7296,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "105",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-20T00:00:00",
      dataFim: "2024-06-20T00:00:00",
      sequencia: 7296,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "105",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-21T00:00:00",
      dataFim: "2024-06-21T00:00:00",
      sequencia: 7296,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "105",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-25T00:00:00",
      dataFim: "2024-06-25T00:00:00",
      sequencia: 7296,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "105",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-12T00:00:00",
      dataFim: "2024-06-11T12:00:00",
      sequencia: 7296,
      diaParcial: true,
      periodo: "",
      tipoFalta: "Falta",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "106",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-14T00:00:00",
      dataFim: "2024-06-14T00:00:00",
      sequencia: 7334,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "109",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-02-12T00:00:00",
      dataFim: "2024-02-12T00:00:00",
      sequencia: 7101,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "109",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-01T00:00:00",
      dataFim: "2024-04-01T00:00:00",
      sequencia: 7188,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "109",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-05-31T00:00:00",
      dataFim: "2024-05-31T00:00:00",
      sequencia: 7234,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "109",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-25T00:00:00",
      dataFim: "2024-06-25T00:00:00",
      sequencia: 7336,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "109",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-26T00:00:00",
      dataFim: "2024-06-26T00:00:00",
      sequencia: 7336,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "109",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-27T00:00:00",
      dataFim: "2024-06-27T00:00:00",
      sequencia: 7336,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "109",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-28T00:00:00",
      dataFim: "2024-06-28T00:00:00",
      sequencia: 7336,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "110",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-02-12T00:00:00",
      dataFim: "2024-02-12T00:00:00",
      sequencia: 7102,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "110",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-01T00:00:00",
      dataFim: "2024-04-01T00:00:00",
      sequencia: 7203,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "110",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-02T00:00:00",
      dataFim: "2024-04-02T00:00:00",
      sequencia: 7203,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "110",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-03T00:00:00",
      dataFim: "2024-04-03T00:00:00",
      sequencia: 7203,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "110",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-04T00:00:00",
      dataFim: "2024-04-04T00:00:00",
      sequencia: 7203,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "110",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-05T00:00:00",
      dataFim: "2024-04-05T00:00:00",
      sequencia: 7203,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "110",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-08T00:00:00",
      dataFim: "2024-04-08T00:00:00",
      sequencia: 7203,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "110",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-09T00:00:00",
      dataFim: "2024-04-09T00:00:00",
      sequencia: 7203,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "110",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-12T00:00:00",
      dataFim: "2024-06-12T00:00:00",
      sequencia: 7338,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "111",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-01-02T00:00:00",
      dataFim: "2024-01-02T00:00:00",
      sequencia: 7060,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "111",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-26T00:00:00",
      dataFim: "2024-04-26T00:00:00",
      sequencia: 7190,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "111",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-29T00:00:00",
      dataFim: "2024-04-29T00:00:00",
      sequencia: 7190,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "111",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-30T00:00:00",
      dataFim: "2024-04-30T00:00:00",
      sequencia: 7190,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "111",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-05-02T00:00:00",
      dataFim: "2024-05-02T00:00:00",
      sequencia: 7236,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "111",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-05-03T00:00:00",
      dataFim: "2024-05-03T00:00:00",
      sequencia: 7236,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "111",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-28T00:00:00",
      dataFim: "2024-06-28T00:00:00",
      sequencia: 7340,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "111",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-11T00:00:00",
      dataFim: "2024-06-10T12:00:00",
      sequencia: 7340,
      diaParcial: true,
      periodo: "",
      tipoFalta: "Falta",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "113",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-01-02T00:00:00",
      dataFim: "2024-01-02T00:00:00",
      sequencia: 7061,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "113",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-01-03T00:00:00",
      dataFim: "2024-01-03T00:00:00",
      sequencia: 7061,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "113",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-01-04T00:00:00",
      dataFim: "2024-01-04T00:00:00",
      sequencia: 7061,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "113",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-01-05T00:00:00",
      dataFim: "2024-01-05T00:00:00",
      sequencia: 7061,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "113",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-05-31T00:00:00",
      dataFim: "2024-05-31T00:00:00",
      sequencia: 7237,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "113",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-25T00:00:00",
      dataFim: "2024-06-25T00:00:00",
      sequencia: 7342,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "113",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-26T00:00:00",
      dataFim: "2024-06-26T00:00:00",
      sequencia: 7342,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "113",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-27T00:00:00",
      dataFim: "2024-06-27T00:00:00",
      sequencia: 7342,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "113",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-28T00:00:00",
      dataFim: "2024-06-28T00:00:00",
      sequencia: 7342,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "114",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-01-26T00:00:00",
      dataFim: "2024-01-26T00:00:00",
      sequencia: 7062,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "114",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-03-04T00:00:00",
      dataFim: "2024-03-04T00:00:00",
      sequencia: 7146,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "114",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-03-05T00:00:00",
      dataFim: "2024-03-05T00:00:00",
      sequencia: 7146,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "114",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-25T00:00:00",
      dataFim: "2024-06-25T00:00:00",
      sequencia: 7344,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "114",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-26T00:00:00",
      dataFim: "2024-06-26T00:00:00",
      sequencia: 7344,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "114",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-27T00:00:00",
      dataFim: "2024-06-27T00:00:00",
      sequencia: 7344,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "114",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-28T00:00:00",
      dataFim: "2024-06-28T00:00:00",
      sequencia: 7344,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "116",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-01-02T00:00:00",
      dataFim: "2024-01-02T00:00:00",
      sequencia: 7063,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "116",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-03-11T00:00:00",
      dataFim: "2024-03-11T00:00:00",
      sequencia: 7147,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "116",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-03-12T00:00:00",
      dataFim: "2024-03-12T00:00:00",
      sequencia: 7147,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "116",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-03-13T00:00:00",
      dataFim: "2024-03-13T00:00:00",
      sequencia: 7147,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "116",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-03-14T00:00:00",
      dataFim: "2024-03-14T00:00:00",
      sequencia: 7147,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "116",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-03-15T00:00:00",
      dataFim: "2024-03-15T00:00:00",
      sequencia: 7147,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "116",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-26T00:00:00",
      dataFim: "2024-04-26T00:00:00",
      sequencia: 7193,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "116",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-05-15T00:00:00",
      dataFim: "2024-05-15T00:00:00",
      sequencia: 7239,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "116",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-12T00:00:00",
      dataFim: "2024-06-12T00:00:00",
      sequencia: 7346,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "116",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-01-18T00:00:00",
      dataFim: "2024-01-17T12:00:00",
      sequencia: 7063,
      diaParcial: true,
      periodo: "",
      tipoFalta: "Falta",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "116",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-03-28T00:00:00",
      dataFim: "2024-03-27T12:00:00",
      sequencia: 7147,
      diaParcial: true,
      periodo: "",
      tipoFalta: "Falta",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "116",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-05-22T00:00:00",
      dataFim: "2024-05-21T12:00:00",
      sequencia: 7239,
      diaParcial: true,
      periodo: "",
      tipoFalta: "Falta",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "116",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-05-24T00:00:00",
      dataFim: "2024-05-23T12:00:00",
      sequencia: 7239,
      diaParcial: true,
      periodo: "",
      tipoFalta: "Falta",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "119",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-03-27T00:00:00",
      dataFim: "2024-03-27T00:00:00",
      sequencia: 7148,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "119",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-03-28T00:00:00",
      dataFim: "2024-03-28T00:00:00",
      sequencia: 7148,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "119",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-01T00:00:00",
      dataFim: "2024-04-01T00:00:00",
      sequencia: 7194,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "119",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-02T00:00:00",
      dataFim: "2024-04-02T00:00:00",
      sequencia: 7194,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "119",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-05-31T00:00:00",
      dataFim: "2024-05-31T00:00:00",
      sequencia: 7240,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "120",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-01-02T00:00:00",
      dataFim: "2024-01-02T00:00:00",
      sequencia: 7066,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "120",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-01-03T00:00:00",
      dataFim: "2024-01-03T00:00:00",
      sequencia: 7066,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "120",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-01-04T00:00:00",
      dataFim: "2024-01-04T00:00:00",
      sequencia: 7066,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "120",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-01-05T00:00:00",
      dataFim: "2024-01-05T00:00:00",
      sequencia: 7066,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "120",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-02-12T00:00:00",
      dataFim: "2024-02-12T00:00:00",
      sequencia: 7109,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "120",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-25T00:00:00",
      dataFim: "2024-06-25T00:00:00",
      sequencia: 7350,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "120",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-26T00:00:00",
      dataFim: "2024-06-26T00:00:00",
      sequencia: 7350,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "120",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-27T00:00:00",
      dataFim: "2024-06-27T00:00:00",
      sequencia: 7350,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "120",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-28T00:00:00",
      dataFim: "2024-06-28T00:00:00",
      sequencia: 7350,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "121",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-16T00:00:00",
      dataFim: "2024-04-16T00:00:00",
      sequencia: 7196,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "121",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-17T00:00:00",
      dataFim: "2024-04-17T00:00:00",
      sequencia: 7196,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "121",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-18T00:00:00",
      dataFim: "2024-04-18T00:00:00",
      sequencia: 7196,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "121",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-19T00:00:00",
      dataFim: "2024-04-19T00:00:00",
      sequencia: 7196,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "121",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-22T00:00:00",
      dataFim: "2024-04-22T00:00:00",
      sequencia: 7196,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "121",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-23T00:00:00",
      dataFim: "2024-04-23T00:00:00",
      sequencia: 7196,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "121",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-24T00:00:00",
      dataFim: "2024-04-24T00:00:00",
      sequencia: 7196,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "121",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-26T00:00:00",
      dataFim: "2024-04-26T00:00:00",
      sequencia: 7196,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "121",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-29T00:00:00",
      dataFim: "2024-04-29T00:00:00",
      sequencia: 7196,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "121",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-04-30T00:00:00",
      dataFim: "2024-04-30T00:00:00",
      sequencia: 7196,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "121",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-05-02T00:00:00",
      dataFim: "2024-05-02T00:00:00",
      sequencia: 7242,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "121",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-05-03T00:00:00",
      dataFim: "2024-05-03T00:00:00",
      sequencia: 7242,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "121",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-06-07T00:00:00",
      dataFim: "2024-06-07T00:00:00",
      sequencia: 7352,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "121",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-03-22T00:00:00",
      dataFim: "2024-03-21T12:00:00",
      sequencia: 7150,
      diaParcial: true,
      periodo: "",
      tipoFalta: "Falta",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "121",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-05-06T00:00:00",
      dataFim: "2024-05-05T12:00:00",
      sequencia: 7242,
      diaParcial: true,
      periodo: "",
      tipoFalta: "Falta",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "122",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-05-31T00:00:00",
      dataFim: "2024-05-31T00:00:00",
      sequencia: 7243,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "124",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-05-02T00:00:00",
      dataFim: "2024-05-02T00:00:00",
      sequencia: 7245,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
    {
      id: 0,
      funcionarioId: "124",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2024-05-03T00:00:00",
      dataFim: "2024-05-03T00:00:00",
      sequencia: 7245,
      diaParcial: false,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Originou Falta",
      comprovativo: null,
      aprovacoes: null,
    },
  ];

  const feriasPorAprovar = [
    {
      id: 9,
      funcionarioId: "001",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2025-01-28T00:00:00",
      dataFim: "2025-01-28T00:00:00",
      sequencia: null,
      diaParcial: null,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Solicitação para dia 28 de janeiro",
      comprovativo: null,
      aprovacoes: {
        aprovadorFuncionarioId: 62,
        aprovadoFuncionario: true,
        dataAprovacaoFuncionario: null,
        aprovadorGestorId: null,
        aprovadoGestor: null,
        dataAprovacaoGestor: null,
        aprovadorRHId: null,
        aprovadoRH: null,
        dataAprovacaoRH: null,
        dataPedidoAprovacao: "2025-01-22T09:23:01.40268",
        objetoId: 0,
        tipoEntidadeAprocacao: null,
        justificacaoFuncionario: null,
        justificacaoGestor: null,
        justificacaoRH: null,
      },
    },
    {
      id: 10,
      funcionarioId: "001",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2025-01-29T00:00:00",
      dataFim: "2025-01-29T00:00:00",
      sequencia: null,
      diaParcial: null,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Solicitação para dia 28 de janeiro",
      comprovativo: null,
      aprovacoes: {
        aprovadorFuncionarioId: 62,
        aprovadoFuncionario: true,
        dataAprovacaoFuncionario: null,
        aprovadorGestorId: null,
        aprovadoGestor: null,
        dataAprovacaoGestor: null,
        aprovadorRHId: null,
        aprovadoRH: null,
        dataAprovacaoRH: null,
        dataPedidoAprovacao: "2025-01-22T09:23:01.40268",
        objetoId: 0,
        tipoEntidadeAprocacao: null,
        justificacaoFuncionario: null,
        justificacaoGestor: null,
        justificacaoRH: null,
      },
    },
    {
      id: 11,
      funcionarioId: "002",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2025-01-15T00:00:00",
      dataFim: "2025-01-15T00:00:00",
      sequencia: null,
      diaParcial: null,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Solicitação para dia 28 de janeiro",
      comprovativo: null,
      aprovacoes: {
        aprovadorFuncionarioId: 62,
        aprovadoFuncionario: true,
        dataAprovacaoFuncionario: null,
        aprovadorGestorId: null,
        aprovadoGestor: null,
        dataAprovacaoGestor: null,
        aprovadorRHId: null,
        aprovadoRH: null,
        dataAprovacaoRH: null,
        dataPedidoAprovacao: "2025-01-22T09:23:01.40268",
        objetoId: 0,
        tipoEntidadeAprocacao: null,
        justificacaoFuncionario: null,
        justificacaoGestor: null,
        justificacaoRH: null,
      },
    },
    {
      id: 12,
      funcionarioId: "002",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2025-01-02T00:00:00",
      dataFim: "2025-01-02T00:00:00",
      sequencia: null,
      diaParcial: null,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Solicitação para dia 28 de janeiro",
      comprovativo: null,
      aprovacoes: {
        aprovadorFuncionarioId: 62,
        aprovadoFuncionario: true,
        dataAprovacaoFuncionario: null,
        aprovadorGestorId: null,
        aprovadoGestor: null,
        dataAprovacaoGestor: null,
        aprovadorRHId: null,
        aprovadoRH: null,
        dataAprovacaoRH: null,
        dataPedidoAprovacao: "2025-01-22T09:23:01.40268",
        objetoId: 0,
        tipoEntidadeAprocacao: null,
        justificacaoFuncionario: null,
        justificacaoGestor: null,
        justificacaoRH: null,
      },
    },
    {
      id: 12,
      funcionarioId: "009",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2025-01-02T00:00:00",
      dataFim: "2025-01-02T00:00:00",
      sequencia: null,
      diaParcial: null,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Solicitação para dia 28 de janeiro",
      comprovativo: null,
      aprovacoes: {
        aprovadorFuncionarioId: 62,
        aprovadoFuncionario: true,
        dataAprovacaoFuncionario: null,
        aprovadorGestorId: null,
        aprovadoGestor: null,
        dataAprovacaoGestor: null,
        aprovadorRHId: null,
        aprovadoRH: null,
        dataAprovacaoRH: null,
        dataPedidoAprovacao: "2025-01-22T09:23:01.40268",
        objetoId: 0,
        tipoEntidadeAprocacao: null,
        justificacaoFuncionario: null,
        justificacaoGestor: null,
        justificacaoRH: null,
      },
    },
    {
      id: 13,
      funcionarioId: "009",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2025-01-10T00:00:00",
      dataFim: "2025-01-02T00:00:00",
      sequencia: null,
      diaParcial: null,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Solicitação para dia 28 de janeiro",
      comprovativo: null,
      aprovacoes: {
        aprovadorFuncionarioId: 62,
        aprovadoFuncionario: true,
        dataAprovacaoFuncionario: null,
        aprovadorGestorId: null,
        aprovadoGestor: null,
        dataAprovacaoGestor: null,
        aprovadorRHId: null,
        aprovadoRH: null,
        dataAprovacaoRH: null,
        dataPedidoAprovacao: "2025-01-22T09:23:01.40268",
        objetoId: 0,
        tipoEntidadeAprocacao: null,
        justificacaoFuncionario: null,
        justificacaoGestor: null,
        justificacaoRH: null,
      },
    },
    {
      id: 14,
      funcionarioId: "009",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2025-01-20T00:00:00",
      dataFim: "2025-01-02T00:00:00",
      sequencia: null,
      diaParcial: null,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Solicitação para dia 28 de janeiro",
      comprovativo: null,
      aprovacoes: {
        aprovadorFuncionarioId: 62,
        aprovadoFuncionario: true,
        dataAprovacaoFuncionario: null,
        aprovadorGestorId: null,
        aprovadoGestor: null,
        dataAprovacaoGestor: null,
        aprovadorRHId: null,
        aprovadoRH: null,
        dataAprovacaoRH: null,
        dataPedidoAprovacao: "2025-01-22T09:23:01.40268",
        objetoId: 0,
        tipoEntidadeAprocacao: null,
        justificacaoFuncionario: null,
        justificacaoGestor: null,
        justificacaoRH: null,
      },
    },
    {
      id: 14,
      funcionarioId: "009",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2025-01-20T00:00:00",
      dataFim: "2025-01-02T00:00:00",
      sequencia: null,
      diaParcial: null,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Solicitação para dia 28 de janeiro",
      comprovativo: null,
      aprovacoes: {
        aprovadorFuncionarioId: 62,
        aprovadoFuncionario: true,
        dataAprovacaoFuncionario: null,
        aprovadorGestorId: null,
        aprovadoGestor: null,
        dataAprovacaoGestor: null,
        aprovadorRHId: null,
        aprovadoRH: null,
        dataAprovacaoRH: null,
        dataPedidoAprovacao: "2025-01-22T09:23:01.40268",
        objetoId: 0,
        tipoEntidadeAprocacao: null,
        justificacaoFuncionario: null,
        justificacaoGestor: null,
        justificacaoRH: null,
      },
    },
    {
      id: 15,
      funcionarioId: "029",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2025-01-28T00:00:00",
      dataFim: "2025-01-02T00:00:00",
      sequencia: null,
      diaParcial: null,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Solicitação para dia 28 de janeiro",
      comprovativo: null,
      aprovacoes: {
        aprovadorFuncionarioId: 62,
        aprovadoFuncionario: true,
        dataAprovacaoFuncionario: null,
        aprovadorGestorId: null,
        aprovadoGestor: null,
        dataAprovacaoGestor: null,
        aprovadorRHId: null,
        aprovadoRH: null,
        dataAprovacaoRH: null,
        dataPedidoAprovacao: "2025-01-22T09:23:01.40268",
        objetoId: 0,
        tipoEntidadeAprocacao: null,
        justificacaoFuncionario: null,
        justificacaoGestor: null,
        justificacaoRH: null,
      },
    },
    {
      id: 16,
      funcionarioId: "029",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2025-01-26T00:00:00",
      dataFim: "2025-01-02T00:00:00",
      sequencia: null,
      diaParcial: null,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Solicitação para dia 28 de janeiro",
      comprovativo: null,
      aprovacoes: {
        aprovadorFuncionarioId: 62,
        aprovadoFuncionario: true,
        dataAprovacaoFuncionario: null,
        aprovadorGestorId: null,
        aprovadoGestor: null,
        dataAprovacaoGestor: null,
        aprovadorRHId: null,
        aprovadoRH: null,
        dataAprovacaoRH: null,
        dataPedidoAprovacao: "2025-01-22T09:23:01.40268",
        objetoId: 0,
        tipoEntidadeAprocacao: null,
        justificacaoFuncionario: null,
        justificacaoGestor: null,
        justificacaoRH: null,
      },
    },
    {
      id: 16,
      funcionarioId: "029",
      funcionario: null,
      funcionarioNome: null,
      dataInicio: "2025-02-10T00:00:00",
      dataFim: "2025-01-02T00:00:00",
      sequencia: null,
      diaParcial: null,
      periodo: "",
      tipoFalta: "Ferias",
      nota: "Solicitação para dia 28 de janeiro",
      comprovativo: null,
      aprovacoes: {
        aprovadorFuncionarioId: 62,
        aprovadoFuncionario: true,
        dataAprovacaoFuncionario: null,
        aprovadorGestorId: null,
        aprovadoGestor: null,
        dataAprovacaoGestor: null,
        aprovadorRHId: null,
        aprovadoRH: null,
        dataAprovacaoRH: null,
        dataPedidoAprovacao: "2025-01-22T09:23:01.40268",
        objetoId: 0,
        tipoEntidadeAprocacao: null,
        justificacaoFuncionario: null,
        justificacaoGestor: null,
        justificacaoRH: null,
      },
    },
  ];

  return (
    <>
      <Heading as="h2" size="md">
        Aprovações de Férias
      </Heading>
      <Card mt="5" p="2">
        <CardBody display="flex" flexDirection="column">
          <Selector
            department={department}
            setDepartment={setDepartment}
            month={month}
            setMonth={setMonth}
            year={year}
            setYear={setYear}
            order={order}
            setOrder={setOrder}
            departamentos={departamentos}
            months={months}
            years={years}
          />
          <Flex>
            <CalendarioTable
              funcionarios={funcionarios}
              selectedMonth={month}
              selectedYear={year}
              feriasFaltas={feriasFaltas}
              feriasPorAprovar={feriasPorAprovar}
            />
          </Flex>
        </CardBody>
      </Card>
    </>
  );
}

export default App;
